name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Loguearse en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir y etiquetar la imagen de Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dagro-micro-market:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/dagro-micro-market:latest ${{ secrets.DOCKER_USERNAME }}/dagro-micro-market:${{ github.sha }}

      # 4. Subir la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dagro-micro-market:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dagro-micro-market:${{ github.sha }}

      # 2. Crear el archivo .env con los secrets de GitHub para dagro-micro-market
      # - name: Create .env file for dagro-micro-market
      #   run: |
      #     cat << EOF >> .env
      #     NODE_ENV=
      #     EOF
